// Galician: frequent Castilianisms with the forms of the RAG norm, and
// optional style advice.

import { matchCase, patternRule, w, type Rule } from './util'

// Castilian form → Galician alternatives (Normas ortográficas e morfolóxicas, RAG).
const CASTELANISMOS: Record<string, string[]> = {
  entonces: ['entón'],
  luego: ['logo', 'despois'],
  después: ['despois'],
  siempre: ['sempre'],
  todavía: ['aínda'],
  ahora: ['agora'],
  mientras: ['mentres'],
  también: ['tamén'],
  aunque: ['aínda que', 'malia que'],
  cuando: ['cando'],
  donde: ['onde'],
  mucho: ['moito'],
  mucha: ['moita'],
  muchos: ['moitos'],
  muchas: ['moitas'],
  muy: ['moi'],
  pues: ['pois'],
  hoy: ['hoxe'],
  ayer: ['onte'],
  mañana: ['mañá'],
  gracias: ['grazas'],
  tampoco: ['tampouco'],
  además: ['ademais'],
  alrededor: ['arredor'],
  cualquier: ['calquera'],
  cualquiera: ['calquera'],
  lejos: ['lonxe'],
  abajo: ['abaixo'],
  debajo: ['debaixo'],
  hacia: ['cara a'],
  despacio: ['amodo', 'devagar'],
  tiempo: ['tempo'],
  ciudad: ['cidade'],
  pueblo: ['pobo', 'vila'],
  silla: ['cadeira'],
  lluvia: ['choiva'],
  hijo: ['fillo'],
  hija: ['filla'],
  hijos: ['fillos'],
  mujer: ['muller'],
  hombre: ['home'],
  ojo: ['ollo'],
  ojos: ['ollos'],
  jefe: ['xefe'],
  basura: ['lixo'],
  cuchillo: ['coitelo'],
  apellido: ['apelido'],
  cumpleaños: ['aniversario'],
  hermano: ['irmán'],
  hermana: ['irmá'],
  abuelo: ['avó'],
  abuela: ['avoa'],
  ventana: ['fiestra', 'xanela'],
  pájaro: ['paxaro'],
  perro: ['can'],
  rodilla: ['xeonllo'],
  oreja: ['orella'],
  hoja: ['folla'],
  rojo: ['vermello'],
  amarillo: ['amarelo'],
  naranja: ['laranxa'],
  manzana: ['mazá'],
  pequeño: ['pequeno'],
  mejor: ['mellor'],
  nuevo: ['novo'],
  nueva: ['nova'],
  viejo: ['vello'],
  vieja: ['vella'],
  bien: ['ben'],
  bueno: ['bo', 'ben'],
  buena: ['boa'],
  buenos: ['bos'],
  buenas: ['boas'],
  gente: ['xente'],
  joven: ['novo', 'mozo'],
  jóvenes: ['novos', 'mozos'],
  ayuntamiento: ['concello'],
  iglesia: ['igrexa'],
  escuela: ['escola'],
  colegio: ['colexio'],
  trabajo: ['traballo'],
  trabajar: ['traballar'],
  hacer: ['facer'],
  hecho: ['feito'],
  llegar: ['chegar'],
  llamar: ['chamar'],
  llevar: ['levar'],
  lleno: ['cheo'],
  llorar: ['chorar'],
  llave: ['chave'],
  caballo: ['cabalo'],
  gallina: ['galiña'],
  cielo: ['ceo'],
  suelo: ['chan'],
  fuego: ['lume'],
  fuerte: ['forte'],
  puerta: ['porta'],
  nuestro: ['noso'],
  nuestra: ['nosa'],
  vuestro: ['voso'],
  cuerpo: ['corpo'],
  huevo: ['ovo'],
  hueso: ['óso'],
  nieve: ['neve'],
  diente: ['dente'],
  tierra: ['terra'],
  viento: ['vento'],
  cuento: ['conto'],
  puerto: ['porto'],
  muerte: ['morte'],
  fiesta: ['festa'],
  dinero: ['diñeiro', 'cartos'],
  poco: ['pouco'],
  poca: ['pouca'],
  pocos: ['poucos'],
  otro: ['outro'],
  otra: ['outra'],
  otros: ['outros'],
  otras: ['outras'],
  ya: ['xa'],
  yo: ['eu'],
  ahí: ['aí'],
  allí: ['alí'],
  jamás: ['xamais'],
  según: ['segundo', 'conforme'],
  sin: ['sen'],
  hay: ['hai'],
  fue: ['foi'],
  soy: ['son'],
  tengo: ['teño'],
  tienes: ['tes'],
  tiene: ['ten'],
  tienen: ['teñen'],
  puedo: ['podo'],
  puedes: ['podes'],
  puede: ['pode'],
  pueden: ['poden'],
  quiero: ['quero'],
  quieres: ['queres'],
  quiere: ['quere'],
  hago: ['fago'],
  hace: ['fai'],
  dijo: ['dixo'],
  dice: ['di'],
  voy: ['vou'],
  estoy: ['estou'],
  pienso: ['penso'],
  siento: ['sinto'],
  vengo: ['veño'],
  viene: ['vén'],
  vienen: ['veñen'],
  mismo: ['mesmo'],
  misma: ['mesma'],
  blanco: ['branco'],
  caliente: ['quente'],
  limpio: ['limpo'],
  noche: ['noite'],
  queso: ['queixo'],
  zanahoria: ['cenoria'],
  cebolla: ['cebola'],
  calabaza: ['cabaza'],
  mantequilla: ['manteiga'],
  azúcar: ['azucre'],
  cerdo: ['porco'],
  oveja: ['ovella'],
  conejo: ['coello'],
  mariposa: ['bolboreta'],
  abeja: ['abella'],
  hormiga: ['formiga'],
  ratón: ['rato'],
  pierna: ['perna'],
  espalda: ['costas'],
  hombro: ['ombro'],
  lengua: ['lingua'],
  novio: ['mozo', 'noivo'],
  novia: ['moza', 'noiva'],
  vecino: ['veciño'],
  vecinos: ['veciños'],
  maestro: ['mestre'],
  maestra: ['mestra'],
  examen: ['exame'],
  cuaderno: ['caderno'],
  lápiz: ['lapis'],
  pizarra: ['lousa', 'encerado'],
  asignatura: ['materia'],
  plaza: ['praza'],
  playa: ['praia'],
  árbol: ['árbore'],
  luna: ['lúa'],
  estrella: ['estrela'],
  juego: ['xogo'],
  juguete: ['xoguete'],
  vacaciones: ['vacacións'],
  invierno: ['inverno'],
  otoño: ['outono'],
  enero: ['xaneiro'],
  febrero: ['febreiro'],
  mayo: ['maio'],
  junio: ['xuño'],
  julio: ['xullo'],
  septiembre: ['setembro'],
  octubre: ['outubro'],
  noviembre: ['novembro'],
  diciembre: ['decembro'],
  lunes: ['luns'],
  miércoles: ['mércores'],
  jueves: ['xoves'],
  viernes: ['venres'],
  cuatro: ['catro'],
  siete: ['sete'],
  ocho: ['oito'],
  nueve: ['nove'],
  diez: ['dez'],
  veinte: ['vinte'],
  treinta: ['trinta'],
  cuarenta: ['corenta'],
  cien: ['cen'],
  primero: ['primeiro'],
  primera: ['primeira'],
  tercero: ['terceiro'],
  alguna: ['algunha'],
  algunos: ['algúns'],
  ninguno: ['ningún'],
  ninguna: ['ningunha'],
  nadie: ['ninguén'],
  alguien: ['alguén'],
  cual: ['cal'],
  cuál: ['cal'],
  cuánto: ['canto'],
  quién: ['quen'],
  quien: ['quen'],
  dónde: ['onde'],
  cómo: ['como'],
  qué: ['que'],
  junto: ['xunto'],
  juntos: ['xuntos'],
  siguiente: ['seguinte'],
  mayor: ['maior'],
}

// Castilianisms that are also rare Galician words ("año" = lamb, "padre" =
// priest, "calle" from calar): only after words that make the reading clear.
const IN_CONTEXT: [string, string, string][] = [
  ['este|ese|aquel|cada|próximo|pasado|último|un', 'año', 'ano'],
  ['estes|eses|aqueles|próximos|pasados|últimos|dous|tres|catro|cinco|seis|sete|oito|nove|dez|moitos|poucos|cantos|\\d+', 'años', 'anos'],
  ['meu|teu|seu|noso|voso', 'padre', 'pai'],
  ['miña|túa|súa|nosa|vosa', 'madre', 'nai'],
  ['meus|teus|seus|nosos|vosos', 'padres', 'pais'],
  ['na|unha|da|pola|esta|esa|nesta|nesa|outra', 'calle', 'rúa'],
  ['unha|outra|esta|esa|calquera|algunha|ningunha', 'cosa', 'cousa'],
  ['moitas|outras|estas|esas|poucas|unhas|tantas', 'cosas', 'cousas'],
  ['da|na|coa|pola|unha|sen|con|beber', 'agua', 'auga'],
  ['no|este|cada|ese|aquel|pasado|próximo', 'verano', 'verán'],
]

const PHRASES: [string, string[]][] = [
  ['desde luego', ['desde logo', 'por suposto']],
  ['a lo mejor', ['se cadra', 'quizais']],
  ['sin embargo', ['porén', 'con todo', 'non obstante']],
  ['o sea', ['ou sexa']],
  ['por supuesto', ['por suposto']],
  ['a veces', ['ás veces']],
  ['de nuevo', ['de novo']],
  ['es decir', ['é dicir']],
  ['por eso', ['por iso']],
]

export const castelanismos: Rule = {
  id: 'gl-castelanismo',
  langs: ['gl'],
  category: 'lexicon',
  kind: 'spelling',
  check: patternRule([
    ...PHRASES.map(([phrase, fix]) => ({ re: w(phrase), fix: () => fix })),
    {
      re: w(Object.keys(CASTELANISMOS).join('|')),
      fix: (m: RegExpExecArray) => CASTELANISMOS[m[0].toLowerCase()],
      // Names ("Pueblo Nuevo") are written with capitals mid-sentence.
      unless: (m: RegExpExecArray, text: string) => {
        if (m[0][0] === m[0][0].toLowerCase()) return false
        const before = text.slice(0, m.index).trimEnd()
        return before !== '' && !/[.!?¿¡:"«“—–-]$/u.test(before)
      },
    },
    ...IN_CONTEXT.map(([prev, word, fix]) => ({ re: w(`(?<=(?:^|[^\\p{L}])(?:${prev}) )${word}`), fix: () => [fix] })),
    // "hasta" is a noun too ("a hasta da bandeira").
    {
      re: w('hasta'),
      fix: () => ['ata'],
      unless: (m: RegExpExecArray, text: string) => /(?:^|[^\p{L}])(?:a|as|unha|unhas|da|das|na|nas|esta|estas|esa|esas|súa|súas)\s+$/iu.test(text.slice(0, m.index)),
    },
  ]),
}

// "pero" is correct Galician; "mais" is often preferred in formal writing.
export const peroMais: Rule = {
  id: 'gl-pero-mais',
  langs: ['gl'],
  category: 'style',
  kind: 'style',
  optional: true,
  check: patternRule([{ re: w('pero'), fix: () => ['mais'], unless: (m, text) => /(?:^|[^\p{L}])(?:o|un|os|uns|do|dun)\s+$/iu.test(text.slice(0, m.index)) }]),
}

// The preposition contracts with the article: "de o" → "do", "en a" → "na",
// "a o" → "ao", "por as" → "polas" (not with "con", where it is optional, nor
// before an infinitive or a gerund: "antes de o facer"; not "de O Grove").
const CONTRACT: Record<string, Record<string, string>> = {
  de: { o: 'do', a: 'da', os: 'dos', as: 'das' },
  en: { o: 'no', a: 'na', os: 'nos', as: 'nas' },
  a: { o: 'ao', a: 'á', os: 'aos', as: 'ás' },
  por: { o: 'polo', a: 'pola', os: 'polos', as: 'polas' },
}
const NOT_INFINITIVE = new Set('muller mar lugar fogar altar colar par bar azar militar familiar particular escolar popular solar polar circular similar nivel xantar pesar parecer amencer amanecer luar ser poder deber haber interior exterior superior inferior anterior posterior maior menor mellor peor profesor director autor lector escritor pintor doutor motor calor color amor tractor ordenador computador'.split(' '))

const STOP = new Set('para e ou que a de en con por sen ata desde se mais pero cando onde como'.split(' '))

export const glContraction: Rule = {
  id: 'gl-contraction',
  langs: ['gl'],
  category: 'grammar',
  kind: 'grammar',
  check(text) {
    const out: ReturnType<Rule['check']> = []
    for (const m of text.matchAll(/(?<![\p{L}'’-])(de|en|a|por) (o|a|os|as)(?![\p{L}'’-])/giu)) {
      const [, prep, art] = m
      if (art !== art.toLowerCase()) continue
      // The next words (up to the end of the clause): an infinitive among the
      // first three means the article belongs to its subject ("despois de o sol saír").
      const next = [...(/^[^,.;:!?()«»"“”]*/u.exec(text.slice(m.index + m[0].length))![0].matchAll(/\p{L}+/gu))].map((x) => x[0].toLowerCase())
      const stop = next.findIndex((word, i) => i > 0 && STOP.has(word))
      next.splice(Math.min(stop < 0 ? 3 : stop, 3))
      if (!next.length) continue
      if (next.some((word) => /(?:ar|er|ir|ír|or|ór|ndo)$/u.test(word) && !NOT_INFINITIVE.has(word))) continue
      if (prep.toLowerCase() === 'de' && /^(?:pé|cabalo)$/.test(next[0])) continue
      const fix = matchCase(prep, CONTRACT[prep.toLowerCase()][art])
      out.push({ from: m.index, to: m.index + m[0].length, replacements: [fix], vars: { word: m[0], fix } })
    }
    return out
  },
}

// Diacritic accents: é (is) / e (and), dá (gives) / da (de + a), vén (comes) /
// ven, está / esta, máis (more) / mais (but), in unambiguous contexts.
export const glDiacritic: Rule = {
  id: 'gl-diacritic',
  langs: ['gl'],
  category: 'confusion',
  kind: 'grammar',
  check: patternRule([
    { re: w('e(?= dicir\\s*[,:])'), fix: () => ['é'], unless: (m, text) => !/(?:^|[,;(—–-])\s*$/u.test(text.slice(0, m.index)) },
    { re: w('(?<=que )e(?= (?:iso|isto|aquilo)\\s*\\?)'), fix: () => ['é'] },
    { re: w('(?<=(?:^|[^\\p{L}])(?:isto|iso|aquilo|el|ela|non|tamén) )e(?= (?:moi|certo|certa|verdade|posible|imposible|necesario|necesaria|importante|doado|doada|difícil|fácil|mellor|obrigatorio|obrigatoria)(?![\\p{L}]))'), fix: () => ['é'] },
    { re: w('(?<=(?:^|[^\\p{L}])(?:me|che|lle|nos|vos|lles|llo|lla|llos|llas|mo|ma|cho|cha) )da'), fix: () => ['dá'] },
    { re: w('da(?= (?:igual|medo|gusto|tempo|xeito|noxo|sono|frío|calor|traballo|paso)(?![\\p{L}]))'), fix: () => ['dá'] },
    { re: w('(?<=(?:^|[^\\p{L}])(?:el|ela|quen|vostede) )ven'), fix: () => ['vén'] },
    { re: w('esta(?= (?:aquí|alí|aí|ben|mal|moi|lonxe|preto|cansado|cansada|contento|contenta|pechado|pechada|aberto|aberta|cheo|chea|baleiro|baleira|feito|feita|claro)(?![\\p{L}]))'), fix: () => ['está'] },
    { re: w('(?<=(?:^|[^\\p{L}])(?:moito|pouco|algo|nada|cada vez|aínda|un pouco|o|os|as|moita|moitos|moitas) )mais'), fix: () => ['máis'] },
    { re: w('mais(?= ca(?![\\p{L}]))'), fix: () => ['máis'] },
  ]),
}

export const glRules: Rule[] = [castelanismos, peroMais, glContraction, glDiacritic]
