// Test cases for the offline rules: each text must produce exactly the listed
// rule matches (rule id and first replacement, or '' when there is none).
// Run with `node scripts/test-spell.mjs`.

import type { Lang } from '../types'
import { runRules } from './index'

type Case = [Lang, string, [string, string][]]

const none: [string, string][] = []

export const CASES: Case[] = [
  // ---------- Common ----------
  ['en', 'This is is a test.', [['repeated-word', 'is']]],
  ['en', 'We had had enough of it.', none],
  ['fr', 'Nous nous levons tôt.', none],
  ['de', 'Die Frau, die die Zeitung liest, lacht.', none],
  ['es', 'La casa casa de mi madre.', [['repeated-word', 'casa']]],
  ['en', 'Two  spaces here.', [['double-space', ' ']]],
  ['en', 'Hello , world.', [['space-before-punctuation', ',']]],
  ['es', 'Hola ,mundo.', [['space-before-punctuation', ', mundo']]],
  ['en', 'Wait ... and see.', none],
  ['en', 'One,two and three.', [['missing-space-after-punctuation', ', two']]],
  ['en', 'The value is 3,5 or 1.5 in total.', none],
  ['en', 'It ended.Then we left.', [['missing-space-after-punctuation', '. Then']]],
  ['en', 'See e.g. the manual and www.example.com today.', none],
  ['es', 'Escríbeme a ana.garcia@example.com mañana.', none],
  ['en', 'this sentence starts in lowercase.', [['sentence-capital', 'This']]],
  ['en', 'It rained. then it stopped.', [['sentence-capital', 'Then']]],
  ['en', 'We met Mr. smith and Dr. jones at 5 p.m. yesterday.', none],
  ['es', 'Trajo lápices, gomas, etc. y cuadernos.', none],
  ['es', 'Vivió en EE.UU. durante años.', none],
  ['de', 'Das war z.B. gut, bzw. sehr gut.', none],
  ['en', 'iPhone sales grew.', none],
  ['es', 'a) Paso de vapor a líquido', none],
  ['gl', 'Preguntou se se podía.', none],
  ['en', 'Go to https://example.com/a,b now.', none],
  // ---------- Spanish ----------
  ['es', 'Haber si vienes mañana.', [['es-a-ver-haber', 'A ver si']]],
  ['es', 'Va haber una fiesta.', [['es-a-ver-haber', 'Va a haber']]],
  ['es', 'Tiene que haber alguien.', none],
  ['es', 'Puede haber quien no lo sepa.', none],
  ['es', 'Debe a ver sido él.', [['es-a-ver-haber', 'Debe haber']]],
  ['es', 'Vamos a ver la película.', none],
  ['es', 'El echo de que no vengas me duele.', [['es-echo-hecho', 'El hecho']]],
  ['es', 'Lo he echo yo.', [['es-echo-hecho', 'he hecho']]],
  ['es', 'Te hecho de menos.', [['es-echo-hecho', 'echo de menos']]],
  ['es', 'Me echo a dormir.', none],
  ['es', 'Espero que no halla sido nada.', [['es-halla-haya', 'haya sido']]],
  ['es', 'Se halla en el centro.', none],
  ['es', 'No es rojo, sino azul.', none],
  ['es', 'Sino vienes, me enfado.', [['es-sino-si-no', 'Si no vienes']]],
  ['es', 'No solo canta, si no que baila.', [['es-sino-si-no', 'sino que']]],
  ['es', 'Ahí que estudiar más.', [['es-ahi-hay', 'Hay que estudiar']]],
  ['es', 'Ahí está tu libro.', none],
  ['es', 'Lo dejé por hay.', [['es-ahi-hay', 'por ahí']]],
  ['es', 'Hoy a sido un buen día.', [['es-a-ha', 'ha sido']]],
  ['es', 'Pasó a estado líquido.', none],
  ['es', '¿Porque no vienes?', [['es-por-que', '¿Por qué']]],
  ['es', 'No vino porque llovía.', none],
  ['es', 'Pienso de que tienes razón.', [['es-dequeismo', 'Pienso que']]],
  ['es', 'Me acuerdo de que llovía.', none],
  ['es', 'Osea, no lo sé.', [['es-joined', 'O sea']]],
  ['es', 'Me gusta sobretodo el mar.', [['es-joined', 'sobre todo']]],
  ['es', 'Llevaba un sobretodo gris.', none],
  ['es', '¿Dónde fuistes ayer?', [['es-preterite-s', 'fuiste']]],
  ['es', 'Estamos tristes hoy.', none],
  ['es', 'Qué hora es?', [['es-question-exclamation', '¿Qué hora es?']]],
  ['es', 'Hola, ¿qué tal? ¡Muy bien!', none],
  ['es', '¡¿Qué dices?!', none],
  ['es', '¿Qué dices. Nada.', [['es-question-exclamation', '']]],
  ['es', 'Hola!', [['es-question-exclamation', '¡Hola!']]],
  ['es', 'Vendrá mañana (?) según dijo.', none],
  ['es', '¡Qué bien, ¿no?', [['es-question-exclamation', '']]],
  // ---------- Galician ----------
  ['gl', 'Entonces fomos á praia.', [['gl-castelanismo', 'Entón']]],
  ['gl', 'Estou muy contento.', [['gl-castelanismo', 'moi']]],
  ['gl', 'Desde luego que si.', [['gl-castelanismo', 'Desde logo']]],
  ['gl', 'Esperamos hasta mañá.', [['gl-castelanismo', 'ata']]],
  ['gl', 'Levantaron a hasta da bandeira.', none],
  ['gl', 'Chamábase Pueblo Nuevo.', none],
  ['gl', 'Quero ir, pero non podo.', none],
  ['gl', 'Que hora é?', none],
  ['gl', '¿Que hora é.', [['es-question-exclamation', '']]],
  ['gl', 'Entón fomos á praia e despois comemos.', none],
  // ---------- French ----------
  ['fr', 'Vraiment? Oui!', [['fr-nbsp', ' ?'], ['fr-nbsp', ' !']]],
  ['fr', 'Vraiment ? Oui !', [['fr-nbsp', ' ?'], ['fr-nbsp', ' !']]],
  ['fr', 'Vraiment ? Oui ! Il dit : bonjour.', none],
  ['fr', 'Rendez-vous à 10:30 sur https://exemple.fr.', none],
  ['fr', 'Il dit «bonjour».', [['fr-nbsp', '« '], ['fr-nbsp', ' »']]],
  ['fr', 'Il y à du monde.', [['fr-confusion', 'Il y a']]],
  ['fr', 'Elle à faim.', [['fr-confusion', 'Elle a']]],
  ['fr', 'Il a mal a partir de midi.', [['fr-confusion', 'à partir de']]],
  ['fr', 'Il a mal à la tête.', none],
  ['fr', 'Sa va bien.', [['fr-confusion', 'Ça va']]],
  ['fr', 'Je fais comme sa.', [['fr-confusion', 'comme ça']]],
  ['fr', 'Elle aime sa maison.', none],
  ['fr', 'Je vois ça mère.', [['fr-confusion', 'sa mère']]],
  ['fr', 'Je viens quelque fois.', [['fr-confusion', 'quelquefois']]],
  ['fr', 'On a pas le temps.', [['fr-confusion', "On n'a pas"]]],
  ['fr', 'On a plus de temps.', none],
  ['fr', 'Si il pleut, on reste.', [['fr-confusion', "S'il"]]],
  ['fr', 'Ils on raison.', [['fr-confusion', 'Ils ont']]],
  ['fr', 'Je leurs ai dit.', [['fr-confusion', 'Je leur']]],
  ['fr', 'Grâce a toi.', [['fr-confusion', 'Grâce à']]],
  ['fr', 'La grâce a touché le public.', none],
  // ---------- German ----------
  ['de', 'Ich glaube, das er kommt.', [['de-das-dass', 'glaube, dass er']]],
  ['de', 'Das Wissen, das er hat, ist groß.', none],
  ['de', 'Das Buch, das er liest, ist gut.', none],
  ['de', 'Ich finde, das ist gut.', none],
  ['de', 'Ihr seit spät.', [['de-seit-seid', 'Ihr seid']]],
  ['de', 'Ich warte seid gestern.', [['de-seit-seid', 'seit gestern']]],
  ['de', 'Seid ruhig!', none],
  ['de', 'Er ist größer wie ich.', [['de-als-wie', 'größer als']]],
  ['de', 'Er ist so groß wie ich.', none],
  ['de', 'Das ist das selbe Auto.', [['de-fixed', 'dasselbe']]],
  // ---------- English ----------
  ['en', 'Your welcome! Thanks for your welcome.', [['en-confusion', "You're welcome"]]],
  ['en', 'You should of told me.', [['en-confusion', 'should have']]],
  ['en', 'It is bigger then that.', [['en-confusion', 'bigger than']]],
  ['en', 'We ate, and then we slept.', none],
  // ---------- Quoted words are mentions ----------
  ['gl', 'Confusión entre «hecho» e «echo».', none],
  ['es', 'El artículo «el» no lleva tilde.', none],
  // ---------- Spanish: diacritic accents ----------
  ['es', 'Se lo di a el.', [['es-contraction', 'a él']]],
  ['es', 'Vengo de el colegio.', [['es-contraction', 'del']]],
  ['es', 'Viajó a El Salvador y de El Cairo volvió.', none],
  ['es', 'Esto es para el.', [['es-diacritic', 'él']]],
  ['es', 'Hablé con el y con ella.', [['es-diacritic', 'él']]],
  ['es', 'El es mi hermano.', [['es-diacritic', 'Él']]],
  ['es', 'Creo que el tiene razón.', [['es-diacritic', 'él']]],
  ['es', 'El tiempo es bueno y el día, largo.', none],
  ['es', 'Los artículos el, la, los y las son determinantes.', none],
  ['es', 'El habla andaluza y el debe de la cuenta.', none],
  ['es', 'Tu eres mi amigo.', [['es-diacritic', 'Tú']]],
  ['es', '¿Y tu? Yo estoy bien.', [['es-diacritic', 'tú']]],
  ['es', 'Hazlo tu mismo.', [['es-diacritic', 'tú']]],
  ['es', 'Entre tu y yo lo haremos.', [['es-diacritic', 'tú']]],
  ['es', 'Tu casa es bonita y tu mismo coche también.', none],
  ['es', 'A mi me gusta el cine.', [['es-diacritic', 'mí']]],
  ['es', 'Es un regalo para mi.', [['es-diacritic', 'mí']]],
  ['es', 'Mi casa y mi mismo barrio.', none],
  ['es', 'Las notas do, re, mi, fa y sol.', none],
  ['es', 'Yo no se nada, pero no se.', [['es-diacritic', 'sé']]],
  ['es', 'No se si vendrá.', [['es-diacritic', 'sé']]],
  ['es', 'Yo se que tienes razón.', [['es-diacritic', 'sé']]],
  ['es', 'No se nadar bien.', [['es-diacritic', 'sé']]],
  ['es', 'No se puede fumar. Yo se lo dije. No se ser de otra manera.', none],
  ['es', 'Tomamos una taza de te con limón.', [['es-diacritic', 'té']]],
  ['es', 'Prefiero el te verde.', [['es-diacritic', 'té']]],
  ['es', 'Te veré mañana, te lo dije.', none],
  ['es', 'Quiero un poco mas de agua.', [['es-diacritic', 'más']]],
  ['es', 'Llegó mas o menos a las diez.', [['es-diacritic', 'más']]],
  ['es', 'Quiso ir, mas no pudo. Habló con Artur Mas.', none],
  ['es', 'Eso si, llega pronto.', [['es-diacritic', 'sí']]],
  ['es', 'Creo que si.', [['es-diacritic', 'sí']]],
  ['es', 'Lo hizo por si mismo.', [['es-diacritic', 'por sí mismo']]],
  ['es', 'Si llueve, no iremos. Dime que si vienes.', none],
  ['es', 'Aún así, lo intentó.', [['es-diacritic', 'Aun así']]],
  ['es', 'Aun no ha llegado.', [['es-diacritic', 'Aún']]],
  ['es', 'Aun no siendo experto, lo arregló.', none],
  ['es', 'Aún no ha llegado; aun así, esperamos.', none],
  ['es', 'Todo esta bien.', [['es-diacritic', 'está']]],
  ['es', 'Esta lista es larga y esta casa es mía.', none],
  // ---------- Spanish: question words ----------
  ['es', '¿Que hora es?', [['es-interrogative', 'Qué']]],
  ['es', '¿Como estás?', [['es-interrogative', 'Cómo']]],
  ['es', '¿Donde vives?', [['es-interrogative', 'Dónde']]],
  ['es', '¿Y cuanto cuesta?', [['es-interrogative', 'cuánto']]],
  ['es', '¡Que bonito!', [['es-interrogative', 'Qué']]],
  ['es', '¿Que no vienes? ¡Que te vaya bien! ¿Cuanto antes, mejor?', none],
  ['es', '¿Como tú? ¿Cuando llegue, me avisas?', none],
  ['es', 'No sé donde vive.', [['es-interrogative', 'dónde']]],
  ['es', 'No sé que hacer.', [['es-interrogative', 'qué']]],
  ['es', 'No sé que sea verdad.', none],
  // ---------- Spanish: agreement ----------
  ['es', 'La problema es grave.', [['es-agreement', 'El problema']]],
  ['es', 'Tengo un clase de inglés.', [['es-agreement', 'una clase']]],
  ['es', 'Los manos frías.', [['es-agreement', 'Las manos']]],
  ['es', 'Vino el canción del verano.', [['es-agreement', 'la canción']]],
  ['es', 'Viene del calle.', [['es-agreement', 'de la calle']]],
  ['es', 'La leche y el sangre.', [['es-agreement', 'la sangre']]],
  ['es', 'Me gusta la aprendizaje.', [['es-agreement', 'el aprendizaje']]],
  ['es', 'Bebió la agua.', [['es-agreement', 'el agua']]],
  ['es', 'Este aula es grande.', [['es-agreement', 'Esta aula']]],
  ['es', 'El agua, el aula y un hacha.', none],
  ['es', 'No quiero que la tema. Que los calles.', none],
  ['es', 'Lo discutimos mano a mano en la Mano Negra.', none],
  ['es', 'La crisis y los días de la semana.', none],
  // ---------- Spanish: dequeísmo, queísmo, laísmo, style ----------
  ['es', 'Creo de que llueve.', [['es-dequeismo', 'Creo que']]],
  ['es', 'Es posible de que llueva.', [['es-dequeismo', 'Es posible que']]],
  ['es', '¿Qué piensas de que venga?', none],
  ['es', 'Me acuerdo que llovía.', [['es-queismo', 'Me acuerdo de que']]],
  ['es', 'Se dio cuenta que era tarde.', [['es-queismo', 'Se dio cuenta de que']]],
  ['es', 'Estoy seguro que vendrá.', [['es-queismo', 'Estoy seguro de que']]],
  ['es', 'A pesar que llovía, salimos.', [['es-queismo', 'A pesar de que']]],
  ['es', 'Se acordó que la reunión sería el lunes. Me alegra que vengas.', none],
  ['es', 'La dije que viniera.', [['es-laismo', 'Le dije que']]],
  ['es', 'A María la di un regalo.', [['es-laismo', 'le di un']]],
  ['es', 'La carta la di a Juan.', none],
  ['es', 'Le lo dije ayer.', [['es-le-lo', 'Se lo']]],
  ['es', 'En base a los datos, decidimos.', [['es-en-base-a', 'Con base en']]],
  ['es', 'Está a nivel del mar.', none],
  // ---------- Months and days ----------
  ['es', 'Nos vemos el Lunes 3 de Marzo.', [['lowercase-month-day', 'lunes'], ['lowercase-month-day', 'marzo']]],
  ['es', 'Lunes: examen. El Viernes Santo y el Domingo de Ramos.', none],
  ['es', 'Nací en el Hospital 12 de Octubre. Julio vino en Mayo.', none],
  ['es', 'Llegó el 5 de Julio.', [['lowercase-month-day', 'julio']]],
  ['gl', 'Vémonos o Luns.', [['lowercase-month-day', 'luns']]],
  ['fr', 'Nous partons en Janvier.', [['lowercase-month-day', 'janvier']]],
  ['fr', 'La fête du 14 Juillet et la planète Mars.', none],
  ['en', 'See you on monday in january.', [['en-capital-month-day', 'Monday'], ['en-capital-month-day', 'January']]],
  ['en', 'We may march in august.', none],
  // ---------- Galician ----------
  ['gl', 'Vou traballar con la gente.', [['gl-castelanismo', 'xente']]],
  ['gl', 'Este año fomos á praia.', [['gl-castelanismo', 'ano']]],
  ['gl', 'O año pace no prado.', none],
  ['gl', 'A miña madre vive en Lugo.', [['gl-castelanismo', 'nai']]],
  ['gl', 'Vou a o cine.', [['gl-contraction', 'ao']]],
  ['gl', 'A casa de o meu avó.', [['gl-contraction', 'do']]],
  ['gl', 'Vivo en a Coruña pero traballo por as tardes.', [['gl-contraction', 'na'], ['gl-contraction', 'polas']]],
  ['gl', 'Antes de o facer, vou de O Grove a A Coruña con o coche.', none],
  ['gl', 'Xente de a pé. Despois de o sol saír, marchamos.', none],
  ['gl', 'Vou a o cine para ver a película.', [['gl-contraction', 'ao']]],
  ['gl', 'Isto e moi bonito.', [['gl-diacritic', 'é']]],
  ['gl', 'Iso, e dicir, o mesmo.', [['gl-diacritic', 'é']]],
  ['gl', 'Eu e ti. Isto e aquilo.', none],
  ['gl', 'Non lle da medo.', [['gl-diacritic', 'dá']]],
  ['gl', 'A casa da avoa e o ton da pena.', none],
  ['gl', 'El ven mañá.', [['gl-diacritic', 'vén']]],
  ['gl', 'Ven aquí, que eles ven a tele.', none],
  ['gl', 'Todo esta ben.', [['gl-diacritic', 'está']]],
  ['gl', 'É moito mais alto.', [['gl-diacritic', 'máis']]],
  ['gl', 'Eu e mais ela. Quero ir, mais non podo.', none],
  // ---------- English ----------
  ['en', 'Its a nice day.', [['en-its-your', "It's"]]],
  ['en', 'Its important to rest.', [['en-its-your', "It's"]]],
  ['en', 'The dog wagged its tail; its very own tail.', none],
  ['en', 'Your going to love it.', [['en-its-your', "You're"]]],
  ['en', 'Your not alone.', [['en-its-your', "You're"]]],
  ['en', 'It is your doing and your right.', none],
  ['en', 'Their is a problem.', [['en-its-your', 'There']]],
  ['en', 'They did it on there own.', [['en-its-your', 'their']]],
  ['en', 'Their house is over there.', none],
  // ---------- French ----------
  ['fr', 'Quant il pleut, je reste.', [['fr-confusion', 'Quand il']]],
  ['fr', 'Quant à moi, je reste.', none],
  ['fr', 'Je viens tout les jours.', [['fr-confusion', 'tous les jours']]],
  ['fr', 'Tout les intéresse.', none],
  ['fr', 'Il faut prévoir à l’avance.', [['fr-pleonasm', 'prévoir']]],
  ['fr', 'Des fruits, comme par exemple des pommes.', [['fr-pleonasm', 'par exemple']]],
  // ---------- German ----------
  ['de', 'Das ist vorallem wichtig.', [['de-fixed', 'vor allem']]],
  ['de', 'Er ist der einzigste Freund.', [['de-einzigste', 'einzige']]],
  ['de', 'Das ist ein Wiederspruch.', [['de-wider-wieder', 'Widerspruch']]],
  ['de', 'Ich wiederhole es wieder.', none],
]

// Returns a description of every failing case.
export function runTests(): string[] {
  const failures: string[] = []
  for (const [lang, text, expected] of CASES) {
    const got = runRules({ text, lang }).map((i) => [i.rule, i.replacements[0] ?? ''])
    const a = JSON.stringify(got)
    const b = JSON.stringify(expected)
    if (a !== b) failures.push(`[${lang}] ${JSON.stringify(text)}\n    expected ${b}\n    got      ${a}`)
  }
  return failures
}
