// Links to the legal pages (public/legal/<lang>/*.html, generated by
// scripts/build-legal.mjs from docs/legal/). Static pages, precached, so they
// open offline; they are in the interface language.

import { language, t } from '../core/i18n'
import { el } from '../ui/widgets'
import './legal.css'

export interface LegalLink {
  id: 'notice' | 'privacy' | 'cookies' | 'terms' | 'accessibility' | 'schools' | 'ai' | 'licenses'
  label: string
  href: string
}

// Relative to the app page (the suite is served from any folder).
const page = (name: string) => `legal/${language}/${name}.html`

export function legalLinks(): LegalLink[] {
  return [
    { id: 'notice', label: t('Legal notice'), href: page('notice') },
    { id: 'privacy', label: t('Privacy'), href: page('privacy') },
    { id: 'cookies', label: t('Cookies and local storage'), href: page('cookies') },
    { id: 'terms', label: t('Terms of use'), href: page('terms') },
    { id: 'accessibility', label: t('Accessibility statement'), href: page('accessibility') },
    { id: 'schools', label: t('Information for schools'), href: page('schools') },
    { id: 'ai', label: t('Artificial intelligence'), href: page('ai') },
    { id: 'licenses', label: t('Third-party licenses'), href: 'legal/licenses.html' },
  ]
}

// A row of links (home screen footer, About dialog). newTab: keep the open document.
export function legalLinksNav(options: { newTab?: boolean; className?: string } = {}): HTMLElement {
  const nav = el('nav', { class: options.className ?? 'legal-links' })
  nav.setAttribute('aria-label', t('Legal information'))
  for (const link of legalLinks()) {
    const a = el('a', { href: link.href, textContent: link.label })
    if (options.newTab) {
      a.target = '_blank'
      a.rel = 'noopener'
    }
    nav.append(a)
  }
  return nav
}

// Footer of the home screen.
export function legalFooter(): HTMLElement {
  return el('footer', { class: 'legal-footer' }, legalLinksNav())
}
